#PBS -P jrs0001
#PBS -l select=1:ncpus=32:ngpus=1:mem=15gb
#PBS -l walltime=00:05:00
#PBS -N MAAIF
#PBS -j oe

# Load dependencies
module load \
    python/3.8.2 \
    magma/2.5.3 \
    glibc/2.14

# Environment setup
# export REPO_PATH=/project/jrs0001/Hidden-Foraging

# if [ -z "$config_path" ]; then
#     config_path="$REPO_PATH/scripts/config.gin"
# fi

module list

cd $PBS_O_WORKDIR

python -c "import pandas as pd; print(f'Pandas version: {pd.__version__}')"
python -c "import numpy as np; print(f'Numpy version: {np.__version__}')"
python -c "import torch; print(f'Torch CUDA: {torch.cuda.is_available()}'); print(f'Torch version: {torch.__version__}')"
python INFG-generate-data-multiple.py \
    --num-repeats 2

#python Hidden-Foraging/hidden-foraging/env/train.py \
#    --config-path $config_path \
#    --job-id ${PBS_JOBID%%.*}
